services:
  users:
    build: .
    image: users
    container_name: users
    ports:
      - 5003:5000
    command: python manage.py run -h 0.0.0.0
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - users-db

  users-db:
    container_name: users-db
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    env_file:
      - .env

  worker:
    image: users
    command: python manage.py run_worker
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - users-db
      - redis

  redis:
    image: redis:6-alpine

  dashboard:
    build:
      context: ./project/dashboard
      dockerfile: Dockerfile
    image: dashboard
    container_name: rq_dashboard
    # expose: 
    #   - 9181
    ports:
      - 9181:9181
    command: rq-dashboard -H redis
    depends_on:
      - redis
    
